datasets/urls.py
from django.urls import path

from .views import * # datasets_list_view

app_name = 'datasets'

urlpatterns = [
    # path(),
    # path('', datasets_list_view, name='datasets-list'),
    path('approximation_datasets/', approx_datasets_list_view, name='approximation_datasets-list'),
    path('classification_datasets/', class_datasets_list_view, name='classification_datasets-list'),

    # # qw или сделать общий урл datasets/<int:id> - но тогда не сделаешь обратный переход через ../?
    # path('approximation_datasets/<int:id>/', dataset_detail_view, name='approximation_dataset_detail_url'),
    # path('classification_datasets/<int:id>/', dataset_detail_view, name='classification_dataset_detail_url'),
    path('<int:id>/', dataset_detail_view, name='dataset_detail_url'),

    path('<int:id>/results/', results_list_view, name='results_list_url'),    # qw /
    path('result/<int:id>/update/', ResultUpdateView.as_view(), name='result_update_url'),
    path('result/<int:id>/delete/', ResultDeleteView.as_view(), name='result_delete_url'),
    path('result/create/', ResultCreateView.as_view(), name='result_create_url'),

]

mlstorage/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('datasets/', include('datasets.urls')),
    path('', include('users.urls')), # авторизация, регистрация и проч.
    path('', index_view, name='main_page_url'),
]

users/urls.py
from django.urls import path


from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login_url'),
    # # path('register/', , name='register_url'), # qw регистрация только через админа?
    path('logout/', my_logout, name='logout_url'),
]

datasets/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User

# TODO: constraints!
# TODO: validation -   > 0 and so on


class Dataset(models.Model):
    # qw
    TYPES = (
        ('Apr', 'Approximation'),
        ('Cls', 'Classification')
    )

    name = models.CharField(max_length=50, verbose_name='Название датасета')
    type = models.CharField(max_length=3, choices=TYPES, verbose_name='Тип')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')  # qw blank, null
    file_link = models.CharField(max_length=150, verbose_name='Ссылка на публикацию')
    instances = models.IntegerField(verbose_name='Количество экземпляров')
    features = models.IntegerField(verbose_name='Количество признаков')
    classes = models.IntegerField(null=True, blank=True, verbose_name='Количество классов')  # т.к. в датасетах для аппроксимации нет классов

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        url = 'datasets:dataset_detail_url'
        return reverse(url, kwargs={'id': self.id})

    # для отображения в панели администрирования
    class Meta:
        verbose_name_plural = "Датасеты"
        verbose_name = "Датасет"


class Result(models.Model):
    # qw CASCADE?
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='User', verbose_name='Пользователь') # todo User (import?)
    dataset_id = models.ForeignKey(Dataset, on_delete=models.CASCADE, related_name='Dataset', verbose_name='Датасет')
    algorithm = models.CharField(max_length=100, verbose_name='Алгоритм') # qw max_length
    # qw blank, null
    # типа чтобы можно было внести только тестовые результаты, если отсутствуют результаты обучения, и наоборот?
    learning_result = models.FloatField(blank=True, null=True, verbose_name='Результаты при обучении', )
    test_result = models.FloatField(blank=True, null=True, verbose_name='Результаты при тестировании')
    # FloatField? решила всё-таки сделать целым
    features = models.IntegerField(verbose_name='Количество признаков')
    rules = models.IntegerField(verbose_name='Количество правил')

    # методика эксперимента
    # METHODS = ()? choices? text or char?
    method = models.TextField(verbose_name='Методика эксперимента')

    def __str__(self):
        return f'{self.user_id.last_name} {self.user_id.first_name} - {self.dataset_id.name} - {self.algorithm}'

    def get_delete_url(self):
        return reverse('datasets:result_delete_url', kwargs={'id': self.id})

    def get_update_url(self):
        return reverse('datasets:result_update_url', kwargs={'id': self.id})

    # для отображения в панели администрирования
    class Meta:
        verbose_name_plural = "Результаты"
        verbose_name = "Результат"
        # ordering = ['learning_result']

datasets/forms.py
from django import forms
from django.forms.widgets import Input

from .models import Result


class ResultModelForm(forms.ModelForm):
    class Meta:
        model = Result
        exclude = ['user_id']
        # fields = ['algorithm',
        #           'learning_result',
        #           'test_result',
        #           'features',
        #           'rules',
        #           'method',
        #           # 'dataset_id',
        #           # 'user_id'
        #           ]
        widgets = {'dataset_id': forms.HiddenInput()}
        # widgets = {'dataset_id': Input(attrs={'hidden': 'True'}), 'user_id': Input(attrs={'hidden': 'True'})}

    # def clean_user_id(self, request):
    #     # data = self.cleaned_data['user_id']
    #     return request.user

    # def clean_dataset_id(self):
    #     pass
# def __init__(self, user, dataset, *args, **kwargs):
    #     super(ResultModelForm, self).__init__(*args, **kwargs)
    #     self.user_id = user
    #     self.dataset_id = dataset

datasets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Dataset, Result
from django.views.generic import View, CreateView
from .forms import ResultModelForm
from django.contrib.auth.models import User


@login_required
def class_datasets_list_view(request):
    datasets = Dataset.objects.filter(type='Cls')
    context = {'datasets': datasets}
    return render(request, 'datasets/classification_datasets_list.html', context)


@login_required
def approx_datasets_list_view(request):
    datasets = Dataset.objects.filter(type='Apr')
    context = {'datasets': datasets}
    return render(request, 'datasets/approximation_datasets_list.html', context)


@login_required
def dataset_detail_view(request, id):
    dataset = get_object_or_404(Dataset, id=id)
    # результаты сортируются по полю learning_result в порядке по убыванию (от большего к меньшему - от лучшего к худшему)
    results = Result.objects.filter(dataset_id=dataset.id).order_by('-learning_result')
    context = {'dataset': dataset, 'results': results}
    template_name = 'datasets/base_detail_view.html'  # qw
    if dataset.type == 'Apr':
        template_name = 'datasets/approximation_dataset_detail.html'
    elif dataset.type == 'Cls':
        template_name = 'datasets/classification_dataset_detail.html'
    return render(request, template_name, context)


# Results views
def owns_result(request, owner_id):
    """
    Проверяет, является ли запрашивающий пользователь владельцем запрашиваемого результата
    Если нет, то выкидывает 403 ошибку
    :param request:
    :param owner_id:
    :return:
    """
    print(request.user.id)
    print(owner_id)
    if request.user.id == owner_id:
        return
    else:
        raise PermissionDenied


class ResultCreateView(LoginRequiredMixin, View):
    template_name = 'datasets/result_create.html'
    form_class = ResultModelForm

    def get(self, request):
        dataset_name = request.GET['dataset']
        ds = Dataset.objects.get(name__iexact=dataset_name)
        form = self.form_class(initial={'dataset_id': ds})
        return render(request, self.template_name, {'form': form, "dataset": ds})

    def post(self, request):
        bound_form = self.form_class(request.POST)

        if bound_form.is_valid():
            result = bound_form.save(commit=False)
            result.user_id = request.user
            result.save()
            return redirect(result.dataset_id)
        return render(request, self.template_name, context={'form': bound_form})


# TODO: доступ только авторизованным пользователям + только пользователям, которым принадлежит результат
class ResultDeleteView(View):
    model = ResultModelForm
    template_name = 'datasets/result_delete.html'

    def get(self, request, id):
        result = get_object_or_404(Result, id=id)
        owns_result(request, result.user_id.id)
        return render(request, self.template_name, {'result': result})

    def post(self, request, id):
        result = get_object_or_404(Result, id=id)
        owns_result(request, result.user_id.id)
        redir_dataset = result.dataset_id
        result.delete()
        return redirect(redir_dataset)


# TODO: доступ только авторизованным пользователям + только пользователям, которым принадлежит результат
class ResultUpdateView(View):
    model = Result
    model_form = ResultModelForm
    template = 'datasets/result_update.html'

    def get(self, request, id):
        result = get_object_or_404(self.model, id=id)
        owns_result(request, result.user_id.id)
        bound_form = self.model_form(instance=result)
        return render(request, self.template, context={'form': bound_form, self.model.__name__.lower(): result})

    def post(self, request, id):
        result = get_object_or_404(self.model, id=id)
        owns_result(request, result.user_id.id)
        bound_form = self.model_form(request.POST, instance=result)

        if bound_form.is_valid():
            new_result = bound_form.save()
            return redirect(new_result.dataset_id)
        return render(request, self.template, context={'form': bound_form, self.model.__name__.lower(): result})


@login_required
def results_list_view(request, id):
    results = Result.objects.filter(user_id=id)
    user = get_object_or_404(User, id=id)
    # user = User.objects.get(id=id)
    return render(request, 'datasets/results_list.html', {'results': results, 'user': user})



# def owns_result(view_func):
#     def wrapper(request, owner_id):
#         if request.user.id == owner_id:
#             pass
#         else:
#             raise PermissionDenied
#     return wrapper

datasets/templates/datasets/approximation_dataset_detail.html
{% extends 'datasets/base_detail_view.html' %}

datasets/templates/datasets/approximation_datasets_list.html
{%  extends 'datasets/base_datasets.html' %}

{% block title %}
  Датасеты для задачи аппроксимации
{% endblock %}

{% block heading %}
  <!-- <h1>Датасеты для задачи аппроксимации</h1> -->
  Датасеты для задачи аппроксимации
{% endblock %}

datasets/templates/datasets/base_datasets.html
{% extends 'base.html' %}

{% block title %}
  Датасеты
{% endblock %}


{% block content %}
<h1 class="mb-4">{% block heading %}Датасеты{% endblock %}</h1>

{% for dataset in datasets %}
<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">{{ dataset.name }}</h5>
    <p class="card-text"> {{ dataset.description|truncatewords:14}} </p>
    <a href="{{ dataset.get_absolute_url }}" class="btn btn-primary">Перейти к датасету</a>
  </div>
</div>
{% endfor %}
{% endblock %}

datasets/templates/datasets/base_detail_view.html
{% extends 'base.html' %}

{% block title %}
    {{ dataset.name }}
{% endblock %}


{% block content %}
    <h1>{{ dataset.name }}</h1>

    <p class="mb-4 font-weight-light">
        {% if dataset.type == "Apr" %}
            Датасет для задачи аппроксимации
        {% elif dataset.type == "Cls" %}
            Датасет для задачи классификации
        {% endif %}
    </p>

    <hr>
    <p class="lead">
        {{ dataset.description }}
    </p>
    <div class="card">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Оригинальный набор данных ➞ <a href="//{{ dataset.file_link }}" target="_blank"
                                                                       class="badge badge-primary"> здесь</a></li>
            <li class="list-group-item">Количество признаков: <span
                    class="badge badge-info">{{ dataset.features }}</span></li>
            {% if dataset.type == "Cls" %}
                <li class="list-group-item">Количество классов: <span
                        class="badge badge-info">{{ dataset.classes }}</span></li>
            {% endif %}
        </ul>
    </div>
    <br>

    <h2>Результаты</h2>
    {% block results %}
        {% if results %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Пользователь</th>
                        <th scope="col">Алгоритм</th>
                        <th scope="col">
                            {% if dataset.type == "Cls" %}
                                Точность
                            {% elif dataset.type == "Apr" %}
                                RMSE
                            {% endif %}
                            обучения
                        </th>
                        <th scope="col">
                            {% if dataset.type == "Cls" %}
                                Точность
                            {% elif dataset.type == "Apr" %}
                                RMSE
                            {% endif %}
                            тестирования
                        </th>
                        <th scope="col">Количество признаков</th>
                        <th scope="col">Количество правил</th>
                        <th scope="col">Методика эксперимента</th>
                        <th scope="col"></th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for result in  results %}
                        <tr>
                            <td><a href="{% url 'datasets:results_list_url' id=result.user_id.id %}" class="text-primary" title="{{ result.user_id.get_full_name }}">{{ result.user_id.username }}</a></td>
                            <td>{{ result.algorithm }}</td>
                            <td>{{ result.learning_result }}</td>
                            <td>{{ result.test_result }}</td>
                            <td>{{ result.features }}</td>
                            <td>{{ result.rules }}</td>
                            <td>{{ result.method }}</td>
                            <td>
                                {% if result.user_id.id == request.user.id %}
                                    <a href="{{ result.get_update_url }}" class="btn btn-sm btn-info mb-1 mt-1">Редактировать</a>
                                    <a href="{{ result.get_delete_url }}" class="btn btn-sm btn-danger mb-1 mt-1">Удалить</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p class="mt-3 text-muted">Результатов пока нет...</p>
        {% endif %}
        <div class="text-center mt-3 mb-3">
            <a class="btn btn-primary" href="{% url 'datasets:result_create_url' %}?dataset={{ dataset }}"
               role="button">Добавить свой результат</a>
        </div>

    {% endblock %}

{% endblock %}

datasets/templates/datasets/classification_dataset_detail.html
{% extends 'datasets/base_detail_view.html' %}

datasets/templates/datasets/classification_datasets_list.html
{%  extends 'datasets/base_datasets.html' %}

{% block title %}
  Датасеты для задачи классификации
{% endblock %}

{% block heading %}
  Датасеты для задачи классификации
{% endblock %}

datasets/templates/datasets/result_create.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="text-center mt-5 mb-5">Добавить результат для "{{ dataset }}"</h1>

    <div class="row justify-content-center">

        <div class="col-5">
            <form class="" action="." method="post">
                {% csrf_token %}
                <div class="form-group">
                    {% for field in form %}
                        <div class="form-group">
                            {% if field.errors %}
                                <div class="alert alert-danger">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                            {#        не давать пользователю возмжоность заполнить поля "датасет" и "пользователь"#}
                            {#        {% if field.name != "dataset_id" and field.name != "user_id" %}#}
                            {% if field.name != "dataset_id" %}

                                {{ field.label }}
                            {% endif %}

                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="text-center mt-4">
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </div>
            </form>

        </div>
    </div>

{% endblock %}


{#{% block content %}#}
{##}
{#<form action="." method='POST'> {% csrf_token %}#}
{#	{{ form.as_p }}#}
{#	<input type="submit" value="Save">#}
{#</form>#}
{##}
{#<!-- action - куда перенесёт после сабмита (к-то ссылка); csrf_token - безопасность джанго, без токена не робит -->#}
{#<!--<form action='.' method="POST"> {% csrf_token %}#}
{#	<input type="text" name="title" placeholder="Your title">#}
{#	<input type="submit" value="Save">#}
{#</form> -->#}
{#<!-- <form method='POST'> {% csrf_token %}#}
{#	{{ form.as_p }}#}
{#	<input type="submit" value="Save">#}
{#</form> -->#}
{#{% endblock %}#}

datasets/templates/datasets/result_delete.html
{% extends 'base.html' %}

{% block title %}
    Удалить результат для "{{ result.dataset_id }}"
{% endblock %}

{% block content %}
    <h1 class="text-center mt-5 mb-5">Удалить результат для "{{ result.dataset_id }}"</h1>
    <form action="." method="post">
        {% csrf_token %}
        <div class="alert alert-warning" role="alert">Вы уверены, что хотите удалить результат для датасета "{{ result.dataset_id }}"?</div>
{#        <h2 class="mb-5">Вы уверены, что хотите удалить результат для "{{ result.dataset_id }}"?</h2>#}
        <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Алгоритм</th>
                        <th scope="col">
                            {% if result.dataset_id.type == "Cls" %}
                                Точность
                            {% elif result.dataset_id.type == "Apr" %}
                                RMSE
                            {% endif %}
                            обучения
                        </th>
                        <th scope="col">
                            {% if result.dataset_id.type == "Cls" %}
                                Точность
                            {% elif result.dataset_id.type == "Apr" %}
                                RMSE
                            {% endif %}
                            тестирования
                        </th>
                        <th scope="col">Количество признаков</th>
                        <th scope="col">Количество правил</th>
                        <th scope="col">Методика эксперимента</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ result.algorithm }}</td>
                            <td>{{ result.learning_result|floatformat }}</td>
                            <td>{{ result.test_result|floatformat }}</td>
                            <td>{{ result.features }}</td>
                            <td>{{ result.rules }}</td>
                            <td>{{ result.method }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <div class="row justify-content-around">
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{{ result.dataset_id.get_absolute_url }}" class="btn btn-info">Отмена</a>
        </div>
    </form>
{% endblock %}

datasets/templates/datasets/result_update.html
{% extends 'base.html' %}

{% block title %}
    Изменить результат
{% endblock %}

{% block content %}
    <h1 class="text-center mt-5 mb-5">Изменение результата для "{{ result.dataset_id }}"</h1>

    <div class="row justify-content-center">

        <div class="col-5">
            <form action="." method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                    <div class="">
                        {% if field.name != "dataset_id" %}

                                {{ field.label }}
                        {% endif %}
                        {{ field }}
                    </div>

                    </div>
                {% endfor %}

                    <div class="text-center mt-4">
                        <button type="submit" class="btn btn-primary">Внести изменения</button>
                    </div>
            </form>

        </div>
    </div>
{% endblock %}

datasets/templates/datasets/results_list.html
{% extends 'base.html' %}

{% block title %}
    Результаты {{ user }}
{% endblock %}

{% block content %}

    <h2 class="mb-4">Результаты пользователя {{ user }}</h2>
        {% if results %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th class="align-middle text-center" scope="col">Датасет</th>
                        <th class="align-middle text-center" scope="col">Алгоритм</th>
                        <th class="align-middle text-center" scope="col">
                            Результаты при обучении
                        </th>
                        <th class="align-middle text-center" scope="col">
                            Результаты при тестировании
                        </th>
                        <th class="align-middle text-center" scope="col">Количество признаков</th>
                        <th class="align-middle text-center" scope="col">Количество правил</th>
                        <th class="align-middle text-center" scope="col">Методика эксперимента</th>
                        <th class="align-middle text-center" scope="col"></th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for result in  results %}
                        <tr>
                            <td class="align-middle text-center"><a class="btn btn-outline-primary btn-sm" href="{{ result.dataset_id.get_absolute_url }}">{{ result.dataset_id }}</a></td>
                            <td class="align-middle">{{ result.algorithm }}</td>
                            <td class="align-middle text-center">{{ result.learning_result }}</td>
                            <td class="align-middle text-center">{{ result.test_result }}</td>
                            <td class="align-middle text-center">{{ result.features }}</td>
                            <td class="align-middle text-center">{{ result.rules }}</td>
                            <td class="align-middle">{{ result.method }}</td>
                            <td class="align-middle">
                                {% if result.user_id.id == request.user.id %}
                                    <a href="{{ result.get_update_url }}" class="btn btn-sm btn-info mb-1 mt-1">Редактировать</a>
                                    <a href="{{ result.get_delete_url }}" class="btn btn-sm btn-danger mb-1 mt-1">Удалить</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p class="mt-3 text-muted">Результатов пока нет...</p>
        {% endif %}
{% endblock %}