datasets/urls.py
from django.urls import path

from .views import * # datasets_list_view

app_name = 'datasets'

urlpatterns = [
    # path(),
    # path('', datasets_list_view, name='datasets-list'),
    path('approximation_datasets/', approx_datasets_list_view, name='approximation_datasets-list'),
    path('classification_datasets/', class_datasets_list_view, name='classification_datasets-list'),

    # # qw или сделать общий урл datasets/<int:id> - но тогда не сделаешь обратный переход через ../?
    # path('approximation_datasets/<int:id>/', dataset_detail_view, name='approximation_dataset_detail_url'),
    # path('classification_datasets/<int:id>/', dataset_detail_view, name='classification_dataset_detail_url'),
    path('<int:id>/', dataset_detail_view, name='dataset_detail_url'),

    path('<int:id>/results/', results_list_view, name='results_list_url'),    # qw /
    path('result/<int:id>/update/', ResultUpdateView.as_view(), name='result_update_url'),
    path('result/<int:id>/delete/', ResultDeleteView.as_view(), name='result_delete_url'),
    path('result/create/', ResultCreateView.as_view(), name='result_create_url'),

]

mlstorage/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('datasets/', include('datasets.urls')),
    path('', include('users.urls')), # авторизация, регистрация и проч.
    path('', index_view, name='main_page_url'),
]

users/urls.py
from django.urls import path


from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login_url'),
    # # path('register/', , name='register_url'), # qw регистрация только через админа?
    path('logout/', my_logout, name='logout_url'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

{% block styles %}
{% endblock %}

    <title>
        {% block title %}
            Datasets Storage
        {% endblock %}
    </title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <!--можно добавить  sticky-top, чтобы навбар был закреплён при скроллинге-->

    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% url 'main_page_url' as main_page_url %}
        <a class="navbar-brand" href="{{ main_page_url }}">Machine learning results storage</a>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == main_page_url %}active{% endif %}"
                       href="{% url 'main_page_url' %}">Главная</a>
                </li>
                {% url 'datasets:classification_datasets-list' as class_datasets_url %}
                {% url 'datasets:approximation_datasets-list' as appr_datasets_url %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.path == class_datasets_url or request.path == appr_datasets_url %}active{% endif %}"
                       href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Датасеты
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ class_datasets_url }}">Для задачи классификации <span
                                class="sr-only">(current)</span></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ appr_datasets_url }}">Для задачи аппроксимации</a>
                    </div>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        {% url 'datasets:results_list_url' id=request.user.id as my_results_url %}
                        <a class="nav-link {% if request.path == my_results_url %}active{% endif %}"
                           href="{{ my_results_url }}" tabindex="-1" aria-disabled="true">Мои результаты</a>
                        <!-- Или "Личный кабинет"? -->
                    </li>

                {% endif %}

            </ul>


            <ul class="navbar-nav mt-2 mt-lg-0">
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link" href="{% url 'users:logout_url' %}" tabindex="-1"
                           aria-disabled="true">Выйти</a>
                    {% else %}
                        {# for redirecting back after login #}
                        <a class="nav-link" href="{% url 'users:login_url' %}?next={{ request.path }}" tabindex="-1"
                           aria-disabled="true">Войти</a>
                        {#            <a class="nav-link" href="{% url 'users:login_url' %}" tabindex="-1" aria-disabled="true">Войти</a>#}
                    {% endif %}
                </li>
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form> -->
        </div>
    </div>

</nav>


<div class="container mt-4"> <!--margin-top=5-->
    <!-- <div class="row">
    <div class="col"> -->
    {% block content %}
        There is no any content for you
    {% endblock %}
    <!-- </div>
  </div> -->
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'datasets/css/styles.css' %}">
{% endblock %}

{% block title %}
    Machine learning results storage
{% endblock %}
{% block content %}
    <h1 class="mb-4">Сайт научной группы исследования нечетких систем</h1>
    <article lang="ru">
        <p>
            Научная группа Томского государственного университета систем управления и радиоэлектроники, функционирующая
            под руководством профессора, доктора технических наук Ходашинского Ильи Александровича, является
            подразделением лаборатории «Съема, анализа и управления биологическими сигналами». Исследования посвящены
            разработке моделей машинного обучения, изучению алгоритмов оптимизации, созданию программных продуктов для
            решения прикладных задач информационной безопасности, медицины и других областей. В составе научной группы
            работают доктор и кандидат технических наук, аспиранты и студенты факультета безопасности.
        </p>
        <p>
            Сайт посвящен сравнению результатов экспериментов, проводимых научной группой, а также предназначен для
            публикации новостей о достижениях участников. В настоящее время ресурс функционирует в тестовом режиме.
        </p>
    </article>
{% endblock %}